### ISSUE TITLE
Parse error on variable-free for-range loops

### ISSUE THREAD

**Issue by qjcg** [jstemmer/gotags#16]
Gotags chokes on the variable-free form of for-range loops that were [introduced in Go 1.4](https://golang.org/doc/go1.4#forrange).

For example, given the following code:

```go
package main

import "fmt"

func main() {
        for range [3]int{} {
                fmt.Println("testing")
        }
}
```

Running gotags produces:

```shell
$ gotags main.go
parse error: main.go:6:6: expected operand, found 'range' (and 1 more errors)

!_TAG_FILE_FORMAT       2
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted/
!_TAG_PROGRAM_AUTHOR    Joel Stemmer    /stemmertech@gmail.com/
!_TAG_PROGRAM_NAME      gotags
!_TAG_PROGRAM_URL       https://github.com/jstemmer/gotags
!_TAG_PROGRAM_VERSION   1.3.0
```

**Comment by jstemmer** [comment]
Gotags uses the go parser from the standard library, so this is probably caused by using a version of gotags that was compiled with an earlier version of Go. Recompiling with the latest version should fix this.

The easiest is probably to run `go get -u github.com/jstemmer/gotags` again.

**Comment by qjcg** [comment]
Hmm, after running `go get -u github.com/jstemmer/gotags` (also `go get -a -u github.com/jstemmer/gotags`), I'm still getting the same parse error.

**Comment by jstemmer** [comment]
You seem to have the right version of go, so it should work. Maybe `go get` works differently than I'd expected.

I just pushed a change to master that adds a test for the variable-free range loop. Go to where the repo was cloned, pull the latests changes and run the tests with `go test`. If the tests pass, a `go install` should be enough.

Otherwise it would be possible for you to actually use a different binary than the one that is installed by the `go` utility. Check with `which gotags` where it is.

**Comment by qjcg** [comment]
Removed everything again, did a `go test` (all ok) / `go install` and now parsing works as expected. Not sure exactly what the source of the error was here, but it seems the issue's resolved for me.
